---
abstract: 'Launchpad.net OAuth 1.0'
author:
  - 'Adam Stokes, C<< <adamjs at cpan.org> >>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.030
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Launchpad
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  perl: 5.008005
resources:
  bugtracker: https://github.com/battlemidget/Net-Launchpad/issues
  homepage: https://github.com/battlemidget/Net-Launchpad
  repository: https://github.com/battlemidget/Net-Launchpad.git
version: 1.0.0
x_contributors:
  - 'Adam Stokes <adam.stokes@ubuntu.com>'
